#!/bin/bash
# Pre-commit hook to validate scripts

echo "--- ./adb/texts/extract-sms.sh check ---"
if ! shellcheck ./adb/texts/extract-sms.sh; then
    echo "ERROR: ShellCheck failed. Fix the script before committing."
    exit 1
fi

echo "--- ./adb/texts/get-sms-fields.sh check ---"
if ! shellcheck ./adb/texts/get-sms-fields.sh; then
    echo "ERROR: ShellCheck failed. Fix the script before committing."
    exit 1
fi

echo "--- ./adb/texts/extract-call.sh check ---"
if ! shellcheck ./adb/calls/extract-call.sh; then
    echo "ERROR: ShellCheck failed. Fix the script before committing."
    exit 1
fi

echo "--- ./adb/texts/get-call-fields.sh check ---"
if ! shellcheck ./adb/calls/get-call-fields.sh; then
    echo "ERROR: ShellCheck failed. Fix the script before committing."
    exit 1
fi

echo "ShellCheck passed. Proceeding with Signed Commit..."
